# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Check python package with flake8

on:
  push:
    paths:
      - "src/**.py"
      - test/*.py
      - .github/workflows/flake8.yml
  pull_request:
    paths:
      - "src/**.py"
      - test/*.py
      - .github/workflows/flake8.yml
  workflow_call:

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.14"

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install '.[dev]'
        pip install -e .
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 src/jinja2_josa_filter/**.py --count --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 src/jinja2_josa_filter/**.py --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

